version: "3"
   
services:
  db:
    image: postgres:14-bullseye
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  web:
    build: 
      context: ./
      dockerfile: ./conf/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./files:/code
    ports:
      - "8000:8000"
    environment:
      - DEBUG=${DEBUGAPP}
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOSTDBNAME=${POSTGRES_HOSTDBNAME}
      - POSTGRES_PORT=${POSTGRES_PORT}
    depends_on:
      - db
